# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b2ee969e0a98ea9fb54d5fbcb220fe6cd01832aafe7b2a235293402173633bf92d3c9c37570776c70c0c82f246450c91a7766cc5c2dd74f68f0bd781aba57b7

test:
  secret_key_base: 05144edf6e07c208b6212473db4616f09e5c5a1f977d7eff40dabd19cd923fa971470c5846905f8c1395d84d60a00d5918bde431c3c93cd80bc41647d3f55ff6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
